### ISSUE TITLE
How can I load maps?

### ISSUE THREAD

**Issue by wolfsmith520-github** [MaciejSzybiak/q2unity#1]
Just don't know how to load maps

**Comment by MaciejSzybiak** [comment]
I added some basic instructions to readme: https://github.com/MaciejSzybiak/q2unity/commit/731ff9e45c2c37525bd9347e2bfb673e9350303c

**Comment by JackMackey** [comment]
When you say "Provide the full path to your Quake II installation in "Full Quake II game path" field (e.g. C:/Quake2)" and "Make sure "Mod folder" is set to "baseq2" I just don't understand what you mean. I'm a beginner. I have quake II installed. What else do I have to do.
